import { Roboto } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/frontend/Navbar";
import Footer from "@/components/frontend/Footer";

export const metadata: Metadata = {
  title: "Vijay Electronics",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      afterSignInUrl="/admin/dashboard"
      afterSignUpUrl="/admin/dashboard"
    >
      <html
        lang="en"
        className={roboto.className}
        suppressHydrationWarning={true}
      >
        <body className="bg-[#F0ECE4]">
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
